stages:
  - build
  - deploy

.build_template: &build_template
  rules:
    - changes:
        - app/**/*
        - components/**/*
        - lib/**/*
        - shared/**/*
        - db/**/*
        - scripts/**/*
        - locales/**/*
        - Dockerfile
        - .dockerignore
        - package.json
        - pnpm-lock.yaml
        - pnpm-workspace.yaml
        - next.config.ts
        - next-env.d.ts
        - tsconfig.build.json
        - drizzle.config.ts
        - tsconfig.json
        - postcss.config.mjs
        - instrumentation.ts
        - proxy.ts
        - .gitlab-ci.yml

build:
  stage: build
  image: reg.mikumikumi.xyz/base/kaniko-builder:latest
  <<: *build_template
  script:
    - export BUILD_DESTINATION="reg.mikumikumi.xyz/kaoru/dashboard:${CI_COMMIT_SHORT_SHA}"
    - build

deploy:
  stage: deploy
  image: reg.mikumikumi.xyz/base/kubectl:latest
  needs: [build]
  <<: *build_template
  script:
    - echo "${KUBECONFIG}" > ~/.kube/config
    - "kubectl set image -n kaoru statefulset/dashboard dashboard=reg.mikumikumi.xyz/kaoru/dashboard:${CI_COMMIT_SHORT_SHA} --kubeconfig ~/.kube/config"
